# Generated by Django 4.2.6 on 2023-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='height',
            field=models.IntegerField(verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='weight',
            field=models.IntegerField(verbose_name='Вес'),
        ),
    ]
