# Generated by Django 4.2.6 on 2023-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_participant_height_alter_participant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='eventstatus',
            field=models.CharField(default='F', max_length=1, verbose_name='Статус спортивного мероприятия'),
        ),
    ]
