# Generated by Django 4.2.6 on 2023-10-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_active_order_alter_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestparticipant',
            name='Participant_count',
        ),
    ]
