# Generated by Django 4.2.6 on 2023-10-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_requestparticipant_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestparticipant',
            name='is_capitan',
            field=models.BooleanField(default=False, verbose_name='Капитан?'),
        ),
    ]
