# Generated by Django 4.2.6 on 2023-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_participant_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='link',
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(default='A', max_length=1, verbose_name='Статус активности'),
        ),
    ]
