# Generated by Django 4.2.6 on 2023-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_participant_link_alter_participant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_order',
        ),
        migrations.AddField(
            model_name='user',
            name='active_participant',
            field=models.IntegerField(default=-1, verbose_name='Активный участник'),
        ),
    ]
