# Generated by Django 4.2.6 on 2023-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_active_order_user_active_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='I', max_length=20, verbose_name='Статус'),
        ),
    ]
