# Generated by Django 4.2.6 on 2023-10-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_participant',
            new_name='active_order',
        ),
    ]
