# Generated by Django 4.2.6 on 2023-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_active_participant_user_active_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_order',
        ),
        migrations.AddField(
            model_name='user',
            name='active_request',
            field=models.IntegerField(default=-1, verbose_name='Активная заявка'),
        ),
    ]
