# Generated by Django 4.2.6 on 2023-11-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_active_order_user_active_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_moderator',
        ),
    ]
