# Generated by Django 4.2.6 on 2023-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_is_manager_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='I', max_length=1, verbose_name='Статус'),
        ),
    ]
