# Generated by Django 4.2.6 on 2023-11-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_moder_request_moder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_request',
        ),
    ]
