# Generated by Django 4.2.4 on 2023-09-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на изображение')),
                ('status', models.CharField(max_length=1, verbose_name='Статус активности')),
                ('bdate', models.DateField(verbose_name='День рождения')),
                ('height', models.CharField(max_length=20, verbose_name='Рост')),
                ('weight', models.CharField(max_length=20, verbose_name='Вес')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее изменение')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создание')),
                ('send', models.DateTimeField(verbose_name='Отправка')),
                ('closed', models.DateTimeField(verbose_name='Закрытие')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.participant', verbose_name='Участник')),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.request', verbose_name='Заявка')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='moder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moder_id', to='lab1.user', verbose_name='ID_Модератор'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='lab1.user', verbose_name='ID_Пользователь'),
        ),
    ]
