# Generated by Django 4.2.4 on 2023-10-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestparticipant',
            name='Participant_count',
        ),
    ]
