# Generated by Django 4.2.4 on 2023-09-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersProducts',
            new_name='RequestParticipant',
        ),
    ]
