# Generated by Django 4.2.4 on 2023-10-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_requestparticipant_participant_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestparticipant',
            unique_together={('Participant', 'Request')},
        ),
    ]
