# Generated by Django 4.2.4 on 2023-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_remove_requestparticipant_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestparticipant',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан?'),
        ),
    ]
