# Generated by Django 4.2.4 on 2023-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_rename_ordersproducts_requestparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='moderator',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
